---
apiVersion: v1
kind: Secret
metadata:
  name: my-quarkus-app-12-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/assemble-platforms-test-2/my-quarkus-app-12-gitops